services:
  gowvp:
    image: gb28181
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 15123:15123 # 管理平台 http 端口
      - 15060:15060 # gb28181 sip tcp 端口
      - 15060:15060/udp # gb28181 sip udp 端口
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
  zlm:
    image: zlmediakit/zlmediakit:master
    restart: always
    ports:
      - 1935:1935 # rtmp
      - 8080:80
      - 8443:443
      - 10000:10000
      - 10000:10000/udp
      - 8000:8000/udp
      - 9000:9000/udp
      - 20050-20100:20050-20100
      - 20050-20100:20050-20100/udp
    volumes:
      - ./conf:/opt/media/conf
