services:
  gowvp:
    image: gb28181
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 18082:18081
    volumes:
      - ./logs:/app/logs
  zlm:
    image: zlmediakit/zlmediakit:master
    restart: always
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
      - 10000:10000
      - 10000:10000/udp
      - 8000:8000/udp
      - 9000:9000/udp
      - 20050-20100:20050-20100
      - 20050-20100:20050-20100/udp
    volumes:
      - ./conf:/opt/media/conf
