// Code generated by gowebx, DO AVOID EDIT.
package smsdb

import (
	"gorm.io/gorm"
	"wvp/internal/core/gb28181"
	"wvp/internal/core/sms"
	"wvp/pkg/gbs"
)

var _ sms.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// MediaServer Get business instance
func (d DB) MediaServer() sms.MediaServerStorer {
	return MediaServer(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {

	if err := d.db.AutoMigrate(
		new(sms.MediaServer),
		new(gb28181.Device),
		new(gbs.Streams),
	); err != nil {
		panic(err)
	}
	return d
}
