// Code generated by gowebx, DO AVOID EDIT.
package media

import "wvp/internal/core/uniqueid"

// Storer data persistence
type Storer interface {
	StreamPush() StreamPushStorer
}

// Core business domain
type Core struct {
	store    Storer
	uniqueID uniqueid.Core
}

// NewCore create business domain
func NewCore(store Storer, uniqueID uniqueid.Core) Core {
	return Core{
		store:    store,
		uniqueID: uniqueID,
	}
}
