version = 1
[Server]
  rtmpSecret = "123"
  [Server.HTTP]
    Port = 15123
    JwtSecret = ""
    Timeout = "60s"

    [Server.HTTP.Pprof]
      Enabled = true
      AccessIps = ['::1', '127.0.0.1']

[Data]
  [Data.Database]
    Dsn = './configs/data.db'
    MaxIdleConns = 1
    MaxOpenConns = 1
    ConnMaxLifetime = '6h0m0s'
    SlowThreshold = '200ms'

[Sip]
  Port = 15062
  Host = "192.168.10.14"
  ID = "3402000000200000001"
  Domain = "3402000000"
  Password = "12345678"

[Media]
  IP = "127.0.0.1"
  HTTPPort = 8080
  Secret = "s1kPE7bzqKeHUaVcp8dCA0jeB8yxyFq4"
  WebHookIP = "192.168.10.14" #"host.docker.internal"
  RTPPortRange = "20000-20500"
  SDPIP = "192.168.10.14"

[Log]
  # 日志存储目录，不能使用特殊符号
  Dir = './logs'
  # 记录级别 debug/info/warn/error
  Level = 'debug'
  # 保留日志多久，超过时间自动删除
  MaxAge = '744h0m0s'
  # 多久时间，分割一个新的日志文件
  RotationTime = '8h0m0s'
  # 多大文件，分割一个新的日志文件(MB)
  RotationSize = 50